# Generated by Django 5.0.3 on 2024-04-01 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_category_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='taxPrice',
        ),
        migrations.AlterField(
            model_name='product',
            name='countInStock',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
